name: Counter Image Demo

on:
  push:
    branches: [ main ] # Trigger on push to specific branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version as an environment variable
        run: echo "VERSION=1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/counter-image:${{ env.VERSION }} -f Dockerfile . 
          docker push ${{ secrets.DOCKER_USERNAME }}/counter-image:${{ env.VERSION }}
  
